### PR TITLE
implement 'SETNX' command

### LINKED ISSUE #294: [Feature] Support the SETNX command
**Describe the solution you'd like**
The [`SETNX`](https://redis.io/docs/latest/commands/setnx/) command should be added to the [`KeysInterface`](https://docs.rs/fred/latest/fred/interfaces/trait.KeysInterface.html) trait.

**Additional context**
I known this command is regarded as deprecated and that we should use `SET` with the `NX` option but I would like to prevent clients from overriding existing keys with Redis [ACL](https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/) which is only possible with the `SETNX` command.

### PR DESCRIPTION
**Pull request by AverageADF**
Resolves #294 

Adding the [`SETNX`](https://redis.io/docs/latest/commands/setnx/) command to `KeysInterface`.

### CODE REVIEW

**Comment by AverageADF** [comment]
Hi @aembke, 
Do you  know  when  this  could be merged / included in a new release?

**Comment by aembke** [comment]
I'll try to get a new release out early next week

**Comment by AverageADF** [comment]
Thanks in advance @aembke !

**Comment by aembke** [comment]
Thanks @AverageADF, this will be cherry-picked into 9.3.0 - https://github.com/aembke/fred.rs/pull/298

**Pull request closed without merging**
